# Generated by Django 4.1.2 on 2022-10-15 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField(default=0)),
                ('date', models.TimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
