# Generated by Django 4.2.1 on 2023-05-28 18:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import sensors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('types', models.CharField(max_length=255)),
                ('change_pendig', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_days', models.IntegerField(default=0)),
                ('week_days', models.IntegerField(default=0)),
                ('hour', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('sensor', models.ForeignKey(default=sensors.models.Sensor.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('type', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('rule', models.IntegerField(default=0)),
                ('sensor', models.ForeignKey(default=sensors.models.Sensor.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('sensor', models.ForeignKey(default=sensors.models.Sensor.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor')),
            ],
        ),
    ]
