# Generated by Django 4.1.2 on 2023-05-07 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_sensor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
