# Generated by Django 4.1.2 on 2023-05-13 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_sensor_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=255)),
                ('value', models.FloatField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
